### ISSUE TITLE
Alias Support

### ISSUE THREAD

**Issue by CommodoreAlpha** [NavalBot/NavalBot-core#28]
The ?play command works great in that it supports all kinds of URLs, but if someone had a list of favourite songs, it might be tiresome to type (or copy+paste, I know this sounds lazy) the URL each time to play the song.

I think it would be nice if aliases could be created for URLs, such that instead of typing "?play exampleURL", one could bind the URL to an alias such as "exampleName" and type "?play exampleName" instead.

**Comment by SunDwarf** [comment]
You can do this, in sort of a limited way, already:

```
?ex is {play exampleName}
```

Then doing `?ex` would play that.
